# Generated by Django 5.0.7 on 2024-07-23 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_options_and_more'),
        ('users', '0004_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='products.product', verbose_name='Товар в корзине'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
